name = "QuantumAcademy"
uuid = "de5eeee4-b72e-4ae6-9bd2-877bdf3311db"
authors = ["Paul Nemec <paul.nemec@tum.de>", "Philip Schwinghammer <ge49wed@mytum.de>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
